services:
  vehicle:
    build:
      context: ./services/vehicle
      dockerfile: Dockerfile
    container_name: vehicle-service
    ports:
      - "50080:50080"
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:50080/vehicles/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

  insurance:
    build:
      context: ./services/insurance
      dockerfile: Dockerfile
    container_name: insurance-service
    ports:
      - "50081:50081"
    environment:
      - VEHICLE_SERVICE_BASE_URL=http://vehicle:50080
    networks:
      - microservices-network
    restart: unless-stopped
    depends_on:
      - vehicle
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:50081/insurances/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

networks:
  microservices-network:
    driver: bridge
