name: Cleanup Old Docker Images

on:
  schedule:
    # Run at 1:00 AM UTC every day
    - cron: '0 1 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        id: repo_name
        run: |
          # Extract owner and repo name
          echo "owner=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 1 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "repo_simple=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Delete old untagged Docker images
        uses: actions/delete-package-versions@v4
        with:
          package-name: '${{ steps.repo_name.outputs.owner }}/${{ steps.repo_name.outputs.repo_simple }}/vehicle'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
          age: '30d'

      - name: Delete old untagged Docker images for insurance service
        uses: actions/delete-package-versions@v4
        with:
          package-name: '${{ steps.repo_name.outputs.owner }}/${{ steps.repo_name.outputs.repo_simple }}/insurance'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
          age: '30d'
